export type InquiryHistory = {
  productName: string;
  quantity: number;
  price: number;
  customizations: boolean;
  status: string;
  action: string;
};

const data: InquiryHistory[] = [
  // {
  //   productName: 'Unbranded Soft Chair',
  //   quantity: 89257,
  //   price: 295.0,
  //   customizations: true,
  //   status: 'new',
  //   action: '/001',
  // },
  // {
  //   productName: 'Modern Wooden Desk',
  //   quantity: 450,
  //   price: 599.99,
  //   customizations: false,
  //   status: 'processing',
  //   action: '/002',
  // },
  // {
  //   productName: 'Ergonomic Office Chair',
  //   quantity: 120,
  //   price: 199.5,
  //   customizations: true,
  //   status: 'completed',
  //   action: '/003',
  // },
  // {
  //   productName: 'Smart Home Thermostat',
  //   quantity: 800,
  //   price: 79.95,
  //   customizations: false,
  //   status: 'pending',
  //   action: '/004',
  // },
  // {
  //   productName: 'Compact Laptop Backpack',
  //   quantity: 300,
  //   price: 49.99,
  //   customizations: true,
  //   status: 'new',
  //   action: '/005',
  // },
  // {
  //   productName: 'Wireless Noise-Canceling Headphones',
  //   quantity: 150,
  //   price: 149.0,
  //   customizations: false,
  //   status: 'processing',
  //   action: '/006',
  // },
  // {
  //   productName: 'Smartphone Holder for Desk',
  //   quantity: 500,
  //   price: 15.5,
  //   customizations: true,
  //   status: 'completed',
  //   action: '/007',
  // },
  // {
  //   productName: 'Stainless Steel Water Bottle',
  //   quantity: 1000,
  //   price: 20.0,
  //   customizations: false,
  //   status: 'pending',
  //   action: '/008',
  // },
  // {
  //   productName: 'Wireless Noise-Canceling Headphones',
  //   quantity: 150,
  //   price: 149.0,
  //   customizations: false,
  //   status: 'processing',
  //   action: '/006',
  // },
  // {
  //   productName: 'Smartphone Holder for Desk',
  //   quantity: 500,
  //   price: 15.5,
  //   customizations: true,
  //   status: 'completed',
  //   action: '/007',
  // },
  // {
  //   productName: 'Stainless Steel Water Bottle ',
  //   quantity: 1000,
  //   price: 20.0,
  //   customizations: false,
  //   status: 'loading',
  //   action: '/008',
  // },
  // {
  //   productName: 'Unbranded Soft Chair',
  //   quantity: 89257,
  //   price: 295.0,
  //   customizations: true,
  //   status: 'new',
  //   action: '/001',
  // },
  // {
  //   productName: 'Modern Wooden Desk',
  //   quantity: 450,
  //   price: 599.99,
  //   customizations: false,
  //   status: 'processing',
  //   action: '/002',
  // },
  // {
  //   productName: 'Ergonomic Office Chair',
  //   quantity: 120,
  //   price: 199.5,
  //   customizations: true,
  //   status: 'completed',
  //   action: '/003',
  // },
  // {
  //   productName: 'Smart Home Thermostat',
  //   quantity: 800,
  //   price: 79.95,
  //   customizations: false,
  //   status: 'pending',
  //   action: '/004',
  // },
  // {
  //   productName: 'Compact Laptop Backpack',
  //   quantity: 300,
  //   price: 49.99,
  //   customizations: true,
  //   status: 'new',
  //   action: '/005',
  // },
  // {
  //   productName: 'Wireless Noise-Canceling Headphones',
  //   quantity: 150,
  //   price: 149.0,
  //   customizations: false,
  //   status: 'processing',
  //   action: '/006',
  // },
  // {
  //   productName: 'Smartphone Holder for Desk',
  //   quantity: 500,
  //   price: 15.5,
  //   customizations: true,
  //   status: 'completed',
  //   action: '/007',
  // },
  // {
  //   productName: 'Stainless Steel Water Bottle',
  //   quantity: 1000,
  //   price: 20.0,
  //   customizations: false,
  //   status: 'pending',
  //   action: '/008',
  // },
  // {
  //   productName: 'Wireless Noise-Canceling Headphones',
  //   quantity: 150,
  //   price: 149.0,
  //   customizations: false,
  //   status: 'processing',
  //   action: '/006',
  // },
  // {
  //   productName: 'Smartphone Holder for Desk',
  //   quantity: 500,
  //   price: 15.5,
  //   customizations: true,
  //   status: 'completed',
  //   action: '/007',
  // },
  // {
  //   productName: 'Stainless Steel Water Bottle',
  //   quantity: 1000,
  //   price: 20.0,
  //   customizations: false,
  //   status: 'pending',
  //   action: '/008',
  // },
];

export default data;
